### ISSUE TITLE
v5.10.7 fails to build with 9.1.1+r273003

### ISSUE THREAD

**Issue by hramrach** [open-power/skiboot#247]
[   52s] hw/fsp/fsp-elog-write.c: In function 'opal_elog_read':
[   52s] hw/fsp/fsp-elog-write.c:213:12: error: taking address of packed member of 'struct errorlog' may result in an unaligned pointer value [-Werror=address-of-packed-member]
[   52s]   213 |   list_del(&log_data->link);
[   52s]       |            ^~~~~~~~~~~~~~~
[   52s] hw/fsp/fsp-elog-write.c:214:43: error: taking address of packed member of 'struct errorlog' may result in an unaligned pointer value [-Werror=address-of-packed-member]
[   52s]   214 |   list_add(&elog_write_to_host_processed, &log_data->link);
[   52s]       |                                           ^~~~~~~~~~~~~~~
[   52s] hw/fsp/fsp-elog-write.c: In function 'opal_elog_ack':
[   52s] hw/fsp/fsp-elog-write.c:237:13: error: taking address of packed member of 'struct errorlog' may result in an unaligned pointer value [-Werror=address-of-packed-member]
[   52s]   237 |    list_del(&record->link);
[   52s]       |             ^~~~~~~~~~~~~
[   52s] hw/fsp/fsp-elog-write.c:254:13: error: taking address of packed member of 'struct errorlog' may result in an unaligned pointer value [-Werror=address-of-packed-member]
[   52s]   254 |    list_del(&record->link);
[   52s]       |             ^~~~~~~~~~~~~
[   52s] hw/fsp/fsp-elog-write.c: In function 'opal_resend_pending_logs':
[   52s] hw/fsp/fsp-elog-write.c:275:46: error: taking address of packed member of 'struct errorlog' may result in an unaligned pointer value [-Werror=address-of-packed-member]
[   52s]   275 |   list_add_tail(&elog_write_to_host_pending, &record->link);
[   52s]       |                                              ^~~~~~~~~~~~~
[   52s] hw/fsp/fsp-elog-write.c: In function 'elog_fsp_commit':
[   52s] hw/fsp/fsp-elog-write.c:370:45: error: taking address of packed member of 'struct errorlog' may result in an unaligned pointer value [-Werror=address-of-packed-member]
[   52s]   370 |   list_add_tail(&elog_write_to_fsp_pending, &buf->link);
[   52s]       |                                             ^~~~~~~~~~
[   52s] hw/fsp/fsp-elog-write.c:376:44: error: taking address of packed member of 'struct errorlog' may result in an unaligned pointer value [-Werror=address-of-packed-member]
[   52s]   376 |  list_add_tail(&elog_write_to_fsp_pending, &buf->link);
[   52s]       |                                            ^~~~~~~~~~
[   52s] hw/fsp/fsp-elog-write.c: In function 'elog_append_write_to_host':
[   52s] hw/fsp/fsp-elog-write.c:385:41: error: taking address of packed member of 'struct errorlog' may result in an unaligned pointer value [-Werror=address-of-packed-member]
[   52s]   385 |   list_add(&elog_write_to_host_pending, &buf->link);
[   52s]       |                                         ^~~~~~~~~~
[   52s] hw/fsp/fsp-elog-write.c:389:46: error: taking address of packed member of 'struct errorlog' may result in an unaligned pointer value [-Werror=address-of-packed-member]
[   52s]   389 |   list_add_tail(&elog_write_to_host_pending, &buf->link);
[   52s]       |                                              ^~~~~~~~~~

**Comment by hramrach** [comment]
Looks like at least this is false positive. The member looks aligned to me
